Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -23,23 +23,46 @@ permissions:
 jobs:
   appimage:
     name: Build AppImage
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-24.04
 
     steps:
       - name: Checkout source
         uses: actions/checkout@v6
 
-      - name: Install system deps
+      - name: Install system deps + Qt
         run: |
           sudo apt-get update
+
           sudo apt-get install -y \
             build-essential \
             pkg-config \
+            protobuf-compiler \
+            wget \
             cmake \
+            ninja-build \
+            file \
             libudev-dev \
             libfuse2 \
-            wget \
-            protobuf-compiler
+            fuse \
+            libxkbcommon-dev \
+            libxkbcommon-x11-0 \
+            libxcb-cursor-dev \
+            libcups2-dev \
+            libglib2.0-0 \
+            libglib2.0-dev \
+            libproxy1v5 \
+            libproxy-dev \
+            qt6-base-dev \
+            qt6-base-dev-tools \
+            qt6-tools-dev \
+            qt6-tools-dev-tools \
+            qt6-wayland \
+            qt6-wayland-dev \
+            libqt6waylandclient6 \
+            qml6-module-qtwayland-compositor \
+            libqt6core5compat6 \
+            libqt6core5compat6-dev \
+            qt6-base-private-dev
 
       - name: Install Rust toolchain
         uses: dtolnay/rust-toolchain@stable
@@ -53,17 +76,16 @@ jobs:
             target
           key: cargo-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
 
-      - name: Install Qt 6.8.0
-        uses: jurplel/install-qt-action@v4
-        with:
-          version: "6.8.0"
-          modules: "qtshadertools qt5compat qtwayland qtsvg"
-          cache: true
-
-      - name: Symlink qsb to /usr/lib/qt6/bin
+      - name: Locate qsb
         run: |
-          sudo mkdir -p /usr/lib/qt6/bin
-          sudo ln -sf "$QT_ROOT_DIR/bin/qsb" /usr/lib/qt6/bin/qsb
+          QSB_PATH="$(command -v qsb)"
+
+          if [ -z "$QSB_PATH" ]; then
+            echo "qsb not found"
+            exit 1
+          fi
+
+          echo "QSB_PATH=$QSB_PATH" >> "$GITHUB_ENV"
 
       - name: Download linuxdeploy + qt plugin
         run: |
@@ -77,11 +99,7 @@ jobs:
 
           chmod +x tools/linuxdeploy tools/linuxdeploy-plugin-qt
 
-          if [[ "6.8.0" == "6.10" ]]; then
-            echo "EXTRA_PLATFORM_PLUGINS=libqwayland.so" >> "$GITHUB_ENV"
-          else
-            echo "EXTRA_PLATFORM_PLUGINS=libqwayland-generic.so" >> "$GITHUB_ENV"
-          fi
+          echo "EXTRA_PLATFORM_PLUGINS=libqwayland-generic.so" >> "$GITHUB_ENV"
 
           echo "EXTRA_QT_MODULES=svg,imageformats,wayland-decoration-client,wayland-graphics-integration-client,wayland-shell-integration" >> "$GITHUB_ENV"
 
